In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df = pd.read_csv('asset/train.csv')
new_df=df.sample(30000)

In [4]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [5]:


ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
86960,What is incest?,Is incest immoral? Why?
114429,What are output devices? What are some examples?,What are some examples of output devices?
234990,What are examples of well-known companies that...,"Soon, I'll be seeing a girl I have a big crush..."
239135,Why does the SS soldier let Norman go in the m...,What does the guitar guy in Mad Max Fury Road do?
192309,Why are Quora moderators deleting all factual ...,How would you explain what is a software to a ...

In [9]:

from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])
len(questions)
cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(30000, 6000)

In [11]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
86960,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114429,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239135,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192309,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
386152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39392,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7580,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:

temp_df['is_duplicate'] = new_df['is_duplicate']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [14]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.743

In [15]:

from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7293333333333333